version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./container/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build:
      context: ./container/php
      dockerfile: DockerFile
    volumes:
      - ./src:/var/www/html

  mysql:
    image: mysql:8.0
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./container/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./doc/api/openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
    environment:
      URL: /openapi.yaml
    depends_on:
      - nginx

volumes:
  mysql-data: